//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4959
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="mapSpecificationScheema.xsd", IsNullable=false)]
public partial class Map {
    
    private MapMapDimentions mapDimentionsField;
    
    private MapSurfaces surfacesField;
    
    private MapPowerups powerupsField;
    
    /// <remarks/>
    public MapMapDimentions MapDimentions {
        get {
            return this.mapDimentionsField;
        }
        set {
            this.mapDimentionsField = value;
        }
    }
    
    /// <remarks/>
    public MapSurfaces Surfaces {
        get {
            return this.surfacesField;
        }
        set {
            this.surfacesField = value;
        }
    }
    
    /// <remarks/>
    public MapPowerups Powerups {
        get {
            return this.powerupsField;
        }
        set {
            this.powerupsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
public partial class MapMapDimentions {
    
    private ushort widthField;
    
    private ushort heightField;
    
    /// <remarks/>
    public ushort Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    public ushort Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
public partial class MapSurfaces {
    
    private MapSurfacesBackgoundPicture backgoundPictureField;
    
    private MapSurfacesWall[] mapWallsField;
    
    private MapSurfacesObsticals obsticalsField;
    
    /// <remarks/>
    public MapSurfacesBackgoundPicture BackgoundPicture {
        get {
            return this.backgoundPictureField;
        }
        set {
            this.backgoundPictureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Wall", IsNullable=false)]
    public MapSurfacesWall[] MapWalls {
        get {
            return this.mapWallsField;
        }
        set {
            this.mapWallsField = value;
        }
    }
    
    /// <remarks/>
    public MapSurfacesObsticals Obsticals {
        get {
            return this.obsticalsField;
        }
        set {
            this.obsticalsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
public partial class MapSurfacesBackgoundPicture {
    
    private string assetNameField;
    
    private byte scaleField;
    
    /// <remarks/>
    public string AssetName {
        get {
            return this.assetNameField;
        }
        set {
            this.assetNameField = value;
        }
    }
    
    /// <remarks/>
    public byte Scale {
        get {
            return this.scaleField;
        }
        set {
            this.scaleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
public partial class MapSurfacesWall {
    
    private MapSurfacesWallAsset assetField;
    
    private string walltypeField;
    
    /// <remarks/>
    public MapSurfacesWallAsset Asset {
        get {
            return this.assetField;
        }
        set {
            this.assetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string walltype {
        get {
            return this.walltypeField;
        }
        set {
            this.walltypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
public partial class MapSurfacesWallAsset {
    
    private ushort heightField;
    
    private ushort widthField;
    
    private MapSurfacesWallAssetScale scaleField;
    
    private decimal rotationField;
    
    private MapSurfacesWallAssetPosition positionField;
    
    private string nameField;
    
    /// <remarks/>
    public ushort Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    public ushort Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    public MapSurfacesWallAssetScale Scale {
        get {
            return this.scaleField;
        }
        set {
            this.scaleField = value;
        }
    }
    
    /// <remarks/>
    public decimal Rotation {
        get {
            return this.rotationField;
        }
        set {
            this.rotationField = value;
        }
    }
    
    /// <remarks/>
    public MapSurfacesWallAssetPosition Position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
public partial class MapSurfacesWallAssetScale {
    
    private decimal xField;
    
    private byte yField;
    
    /// <remarks/>
    public decimal X {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    public byte Y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
public partial class MapSurfacesWallAssetPosition {
    
    private short xField;
    
    private short yField;
    
    /// <remarks/>
    public short X {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    public short Y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
public partial class MapSurfacesObsticals {
    
    private MapSurfacesObsticalsAsset assetField;
    
    /// <remarks/>
    public MapSurfacesObsticalsAsset Asset {
        get {
            return this.assetField;
        }
        set {
            this.assetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
public partial class MapSurfacesObsticalsAsset {
    
    private byte heightField;
    
    private byte widthField;
    
    private MapSurfacesObsticalsAssetScale scaleField;
    
    private MapSurfacesObsticalsAssetPosition positionField;
    
    private string nameField;
    
    /// <remarks/>
    public byte Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    public byte Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    public MapSurfacesObsticalsAssetScale Scale {
        get {
            return this.scaleField;
        }
        set {
            this.scaleField = value;
        }
    }
    
    /// <remarks/>
    public MapSurfacesObsticalsAssetPosition Position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
public partial class MapSurfacesObsticalsAssetScale {
    
    private byte xField;
    
    private byte yField;
    
    /// <remarks/>
    public byte X {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    public byte Y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
public partial class MapSurfacesObsticalsAssetPosition {
    
    private byte xField;
    
    private byte yField;
    
    /// <remarks/>
    public byte X {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    public byte Y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
public partial class MapPowerups {
    
    private MapPowerupsPowerup powerupField;
    
    /// <remarks/>
    public MapPowerupsPowerup Powerup {
        get {
            return this.powerupField;
        }
        set {
            this.powerupField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
public partial class MapPowerupsPowerup {
    
    private MapPowerupsPowerupAsset assetField;
    
    private string powerupTypeField;
    
    /// <remarks/>
    public MapPowerupsPowerupAsset Asset {
        get {
            return this.assetField;
        }
        set {
            this.assetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string powerupType {
        get {
            return this.powerupTypeField;
        }
        set {
            this.powerupTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
public partial class MapPowerupsPowerupAsset {
    
    private byte heightField;
    
    private byte widthField;
    
    private MapPowerupsPowerupAssetScale scaleField;
    
    private MapPowerupsPowerupAssetPosition positionField;
    
    private string nameField;
    
    /// <remarks/>
    public byte Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    public byte Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    public MapPowerupsPowerupAssetScale Scale {
        get {
            return this.scaleField;
        }
        set {
            this.scaleField = value;
        }
    }
    
    /// <remarks/>
    public MapPowerupsPowerupAssetPosition Position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
public partial class MapPowerupsPowerupAssetScale {
    
    private byte xField;
    
    private byte yField;
    
    /// <remarks/>
    public byte X {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    public byte Y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mapSpecificationScheema.xsd")]
public partial class MapPowerupsPowerupAssetPosition {
    
    private byte xField;
    
    private byte yField;
    
    /// <remarks/>
    public byte X {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    public byte Y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
}
